Adding support for comparing object files of the generated app
spouliot/appcompare pull request #1
Opened 2022-06-14 08:16 UTC by ivanpovazan

In order to get better insight into app size comparison as discussed https://github.com/xamarin/xamarin-macios/issues/10249#issuecomment-1154167714.
I have added an additional table generation which breaks down object files sizes and compares them accordingly.

The following has been done:
- A new command line switch has been introduced `--obj-dirs`
    - usage: `--obj-dirs abspath1:abspath2`
- `GetTable` has two versions: one for the app files and the other for the obj files table generation
    - filenames are now stored in the table without the relative path to the app or obj directories (this could potentially introduce problems with files with the same name across different sub directories)
- `ExportMarkdown` and `Gist` now accepts list of tables and generate reports in the new format (every table in its separate subsection)

Future work:
- Include obj files comparison feature into the GUI variant
- Refactor common code (for example `GetTable` method)
- Iron out command line switches
    - idea:
    ```
    appcompare /
    --app1 abspath_to_app:abspath_to_obj /
    --app2 abspath_to_app:abspath_to_obj /
    --obj-dirs true
    ```
    and
    ```
    appcompare /
    --app1 abspath_to_app /
    --app2 abspath_to_app
    ``` 
    - this way it would be more natural to match the paths to app and obj dirs, if --obj-dirs is leftout or `false` then the `abspath_to_obj` could be omitted
    
This is how the new report looks like:
https://gist.github.com/ivanpovazan/f9bb4e05cb2f6291b6c2318b3dacf22f

2022-06-17 13:23 UTC, spouliot requested changes
❤️ it

2022-06-17 13:23 UTC, spouliot commented on Comparer.cs
> +	const string FILTER_OBJ_FILES = "*.o";
minor: I using the mono coding convention (old habits) and constants are defined like normal variables (not all caps).

2022-06-17 13:23 UTC, spouliot commented on Program.cs
> +			tables.Add(Comparer.GetAppCompareTable (app1, app2, mappings));
minor: space before `(`

there's an `.editorconfig` file in the repo, most IDE should adapt to it
and, if not, you should be able to run `dotnet format` to conform to the style

2022-06-17 13:23 UTC, spouliot commented on Program.cs
> +			tables.Add(Comparer.GetAppCompareTable (app1, app2, mappings));
minor: space before `(`

there's an `.editorconfig` file in the repo, most IDE should adapt to it
and, if not, you should be able to run `dotnet format` to conform to the style

2022-06-17 13:23 UTC, spouliot commented on Program.cs
> +			if (!string.IsNullOrEmpty(objDirs)) {
same

2022-06-17 13:23 UTC, spouliot commented on Program.cs
> +			if (!string.IsNullOrEmpty(objDirs)) {
same

2022-06-17 13:23 UTC, spouliot commented on Program.cs
> +				var objDirsSplitted = objDirs.Split(":");
same

2022-06-17 13:23 UTC, spouliot commented on Program.cs
> +				var objDirsSplitted = objDirs.Split(":");
same

2022-06-17 13:58 UTC, ivanpovazan commented
I have corrected the formatting issues, let me know if there is anything else that needs some clean up.

2022-06-17 14:09 UTC, spouliot approved these changes

2022-06-17 14:09 UTC, spouliot commented on Comparer.cs
> +	const string FILTER_OBJ_FILES = "*.o";
minor: I using the mono coding convention (old habits) and constants are defined like normal variables (not all caps).

2022-06-17 14:09 UTC, merged

2022-06-19 21:54 UTC, ivanpovazan commented
hello @spouliot, is there any chance to create a new release which would include this change?
I am asking this so we could update the makefile on the xamarin repo to utilize the obj file compare.

2022-06-21 00:23 UTC, spouliot commented
good idea! I'll do that asap

2022-06-21 00:43 UTC, spouliot commented
@ivanpovazan https://github.com/spouliot/appcompare/releases/tag/2.3.0

2022-06-21 06:48 UTC, ivanpovazan commented
Thank you very much!